### ISSUE TITLE
Subscription Management feature is broken

### ISSUE THREAD

**Issue by alex-418** [BCcampus/custom-wp-notify#42]
Can't move users between the "Subscribed" and "Not Subscribed" select lists. 

[Description of the bug or feature]

Moving a user back and forth between subscribed and non subscribed should work. 

[What you expect/want to happen]

Nothing happens when you try and move a user. 

[What actually happened]

Users stay in the same list. 

1. Login to eypd.bccampus.ca with an account with admin privileges 
2. Visit the Custom WP notify settings page (Settings -> Custom WP Notify)
3. Click on the "Subscription Management" tab 
4. Try to move a user over 

### System Information

- Custom WP Notify: v0.6.0 
- WordPress:  4.9.7

**Comment by paulagaube** [comment]
@kathreenriel @bdolor I explored/tested this issue with the Custom WP Notify plugin not working and confirm that Administrators still cannot "Manage Users" email notifications at all.  (So if a user replies to an auto-notification email and requests to be removed from the auto-email subscription list, we are unable to remove them or move them from the "Subscribed" list to the "Not Subscribed" list.)

However, I tested on eypd.bccampus.ca, and my test "fakeuser" was able to login as a subscriber, go to the "myEYPD" page, and under the "Training" heading, uncheck the box "Get emails when new training opportunities are added". This change then gets automatically "saved" on the myEYPD page, and I confirmed that the user moves from the "Subscribed" to "Not Subscribed" list. So the user is able to remove themselves from the subscription list. 

I can't see where/if an Administrator can modify a user's profile to do this for them.

**Comment by bdolor** [comment]
this is a syntax error and can be resolved by removing the extraneous '/' character when loading the script. (complete via https://github.com/BCcampus/custom-wp-notify/commit/48a6efadd680c4a1f4da36bededf4cd8b7265928)

https://github.com/BCcampus/custom-wp-notify/blob/dev/inc/class-cwpoptions.php#L52

Also note that the dependency has been updated from 2.5.0 to 2.5.5 https://yarnpkg.com/en/package/multiselect-two-sides - bringing this into yarn/npm would shift dependency management to an automated process
